/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.77
 * Generated at: 2022-05-24 08:57:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import a.b.c.com.kosmo.board.vo.KosmoBoardVO;
import a.b.c.com.kosmo.common.CodeUtil;
import java.util.List;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

public final class kosmoBoardSelectAll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.log4j.Logger");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("a.b.c.com.kosmo.board.vo.KosmoBoardVO");
    _jspx_imports_classes.add("org.apache.log4j.LogManager");
    _jspx_imports_classes.add("a.b.c.com.kosmo.common.CodeUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8");
      out.write(" \r\n");
      out.write("\r\n");
	
	Logger logger = LogManager.getLogger(this.getClass());
	logger.info("kosmoBoardSelectAll.jsp 페이지 >>> : ");
	Object obj = request.getAttribute("listAll");
	List<KosmoBoardVO> list = (List<KosmoBoardVO>)obj;
	
	int nCnt = list.size();
	String nCntS = ":::: 전체 조회 건수  " + nCnt + " 건";	

      out.write("     \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/kosmoSpring/js/common.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		// 체크박스 클릭시 작동\r\n");
      out.write("		$(document).on(\"click\", \"#kbnum\", function(){\r\n");
      out.write("			if($(this).prop('checked')){\r\n");
      out.write("				$('.kbnum').prop('checked', false);\r\n");
      out.write("				$(this).prop('checked', true);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 글쓰기 버튼시 작동\r\n");
      out.write("		$(document).on(\"click\", \"#insertBtn\", function(){\r\n");
      out.write("			location.href=\"kosmoBoardInsertForm.yys\";\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// Select All\r\n");
      out.write("		$(document).on(\"click\", \"#selectAllBtn\", function(){		\r\n");
      out.write("			$(\"#boardList\").attr({\"method\":\"GET\", \"action\":\"kosmoBoardSelectAll.yys\"}).submit();		\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// Select\r\n");
      out.write("		$(document).on(\"click\", \"#selectBtn\", function(){\r\n");
      out.write("			// alert(\"selectBtn 클릭 >>> : \");\r\n");
      out.write("			// var chk=$(\".kbnum:checked\").length;\r\n");
      out.write("			// alert(\"chk >> : \"+chk);\r\n");
      out.write("			\r\n");
      out.write("			if($(\".kbnum:checked\").length==0){\r\n");
      out.write("				alert(\"삭제할 글번호 하나를 선택하세요!!\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			$(\"#boardList\").attr({\r\n");
      out.write("				\"method\":\"GET\",\r\n");
      out.write("				\"action\":\"kosmoBoardSelect.yys\",\r\n");
      out.write("				\"enctype\":\"application/x-www-form-urlencoded\"\r\n");
      out.write("			}).submit();\r\n");
      out.write("		});	\r\n");
      out.write("		\r\n");
      out.write("		// Delete\r\n");
      out.write("		$(document).on(\"click\", \"#deletetBtn\", function(){\r\n");
      out.write("			if($('.kbnum:checked').length==0){\r\n");
      out.write("				alert(\"삭제할 글 번호 하나를 선택하세요!!\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			$(\"#boardList\").attr(\r\n");
      out.write("				{\r\n");
      out.write("					\"method\":\"GET\",\r\n");
      out.write("					\"action\":\"kosmoBoardDelete.yys\",\r\n");
      out.write("					\"enctype\":\"application/x-www-form-urlencoded\"\r\n");
      out.write("				}		\r\n");
      out.write("			).submit();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h3>게시판 글 목록</h3>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<form name=\"boardList\" id=\"boardList\">\r\n");
      out.write("<table border=\"1\" align=\"center\">\r\n");
      out.write("<thead>\r\n");
      out.write("<tr>\r\n");
      out.write("<td colspan=\"9\" >");
      out.print( nCntS );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<th><input type=\"checkbox\" name=\"chkAll\" id=\"chkAll\"></th>\r\n");
      out.write("	<th>순번</th>\r\n");
      out.write("	<th>글번호</th>\r\n");
      out.write("	<th>사진</th>\r\n");
      out.write("	<th>글제목</th>\r\n");
      out.write("	<th>이름</th>\r\n");
      out.write("	<th>글내용</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");

for(int i=0; i<nCnt; i++){		
	KosmoBoardVO _kbvo = list.get(i);	

      out.write("\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"tt\">\r\n");
      out.write("		<input type=\"checkbox\" id=\"kbnum\" name=\"kbnum\" class=\"kbnum\" value=");
      out.print( _kbvo.getKbnum() );
      out.write(" >\r\n");
      out.write("	</td>		\r\n");
      out.write("	<td class=\"tt\">");
      out.print( i + 1 );
      out.write("</td>\r\n");
      out.write("	<td class=\"tt\">");
      out.print( _kbvo.getKbnum() );
      out.write(" </td>\r\n");
      out.write("	<td class=\"tt\"><img src=\"/kosmoSpring_YYS/fileupload/board2/");
      out.print( _kbvo.getKbfile() );
      out.write(" \" border=\"1\" width=\"100\" height=\"100\" alt=\"image\"></td>\r\n");
      out.write("	<td class=\"tt\">");
      out.print( _kbvo.getKbsubject() );
      out.write(" </td>\r\n");
      out.write("	<td class=\"tt\">");
      out.print( _kbvo.getKbname() );
      out.write(" </td>\r\n");
      out.write("	<td class=\"tt\">");
      out.print( _kbvo.getKbcontent() );
      out.write(" </td>				\r\n");
      out.write("</tr>	\r\n");

}//end of for

      out.write("	\r\n");
      out.write("<tr>\r\n");
      out.write("	<td colspan=\"9\" align=\"right\">				\r\n");
      out.write("		<input type=\"button\" value=\"글쓰기\" id=\"insertBtn\">\r\n");
      out.write("		<input type=\"button\" value=\"글목록\" id=\"selectAllBtn\">\r\n");
      out.write("		<input type=\"button\" value=\"글내용보기\" id=\"selectBtn\">		\r\n");
      out.write("		<input type=\"button\" value=\"글삭제\" id=\"deletetBtn\"> 								\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>	\r\n");
      out.write("</tbody>	\r\n");
      out.write("</table>\r\n");
      out.write("</form>	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
