/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.77
 * Generated at: 2022-05-02 07:29:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.kosmo.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import a.b.c.com.kosmo.board.vo.BoardVO;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

public final class boardSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.log4j.Logger");
    _jspx_imports_classes.add("a.b.c.com.kosmo.board.vo.BoardVO");
    _jspx_imports_classes.add("org.apache.log4j.LogManager");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- 디바이스에 최적화된 크기로 출력됨 ------------------------------------->\r\n");
      out.write("<meta name=\"viweport\" content=\"width=device-width, iitail-scale=1\">\r\n");
      out.write("<!--  jQuery CDN 불러오기 -->\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function(){	\r\n");
      out.write("		//  type=\"button\" id=\"update_btn\" value=\"수정\"\r\n");
      out.write("		//  type=\"button\" id=\"insert_btn\" value=\"글쓰기\"\r\n");
      out.write("		//  type=\"button\" id=\"selectAllBtn\" value=\"목록\"\r\n");
      out.write("		\r\n");
      out.write("		// 글쓰기 on(매개변수 3개) :: 글쓰기 버튼\r\n");
      out.write("		$(document).on(\"click\", \"#insert_btn\", function(){\r\n");
      out.write("			alert(\"글쓰기 버튼(insert_btn) 클릭 >>> : \");\r\n");
      out.write("			alert(\"board.html으로 이동 >>> : \");\r\n");
      out.write("			location.href=\"/kosServlet_YYS/kosmo/board/board.html\";\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 글목록 on(매개변수 3개) :: \r\n");
      out.write("		$(document).on(\"click\", \"#selectAllBtn\", function(){\r\n");
      out.write("			alert(\"글목록 버튼(selectAllBtn) 클릭 >>> : \");\r\n");
      out.write("			alert(\"콘트롤러로 이동 >>> : \");\r\n");
      out.write("			location.href=\"/kosServlet_YYS/board?isudType=SALL\";\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 수정하기\r\n");
      out.write("		$(document).on(\"click\", \"#update_btn\", function(){\r\n");
      out.write("			alert(\"수정하기(update_btn) 버튼 클릭 >>> : \");\r\n");
      out.write("			alert(\"콘트롤러로 이동 >>> : \");\r\n");
      out.write("			$(\"#f1\").attr({\r\n");
      out.write("				\"action\":\"/kosServlet_YYS/board\",\r\n");
      out.write("				\"method\":\"GET\",\r\n");
      out.write("				\"enctype\":\"application/x-www-form-urlencoded\"\r\n");
      out.write("			}).submit();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 비밀번호 확인하기\r\n");
      out.write("		$(\"#bpwChk\").click(function(){\r\n");
      out.write("			// <input type=\"text\" style=\"width:100%; background-color:#e6e6e6;\" class=\"bpw\" name=\"bpw\" id=\"bpw\"\r\n");
      out.write("			alert(\"비밀번호를 체크하도록 하겠습니다. >>> : \");\r\n");
      out.write("			let urlVal=\"/kosServlet_YYS/board\";\r\n");
      out.write("			let typeVal=\"GET\";\r\n");
      out.write("			let bnumVal=$(\"#bnum\").val();\r\n");
      out.write("			let bpwVal=$(\"#bpw\").val();\r\n");
      out.write("			let isudtypeVal=$(\"#isudType\").val(\"PWCHK\");\r\n");
      out.write("			isudtypeVal=isudtypeVal.val();\r\n");
      out.write("			\r\n");
      out.write("			console.log(\"urlVal >>> : \"+urlVal);\r\n");
      out.write("			console.log(\"typeVal >>> : \"+typeVal);\r\n");
      out.write("			console.log(\"bnumVal >>> : \"+bnumVal);\r\n");
      out.write("			console.log(\"bpwVal >>> : \"+bpwVal);\r\n");
      out.write("			console.log(\"isudType >>> : \"+isudType);\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			if(bpwVal==''){\r\n");
      out.write("				alert(\"비밀번호를 입력하시지 않으셨습니다. >>> : \");\r\n");
      out.write("				$(\"#bpw\").focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:urlVal,\r\n");
      out.write("				type:typeVal,\r\n");
      out.write("				data:{\r\n");
      out.write("					\"bnum\":bnumVal,\r\n");
      out.write("					\"bpw\":bpwVal,\r\n");
      out.write("					\"isudType\":isudtypeVal\r\n");
      out.write("				},\r\n");
      out.write("				success:whenSuccess,\r\n");
      out.write("				error:whenError\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			function whenSuccess(resData){\r\n");
      out.write("				var sVal=$(resData).find(\"result\").text();\r\n");
      out.write("				console.log(\"sVal >>> : \"+sVal);\r\n");
      out.write("				if(sVal=='PW_GOOD'){\r\n");
      out.write("					alert(\"비밀번호가 확인 되었습니다.\");\r\n");
      out.write("					$(\"#bpw\").css(\"background-color\", \"#e6e6e6\");\r\n");
      out.write("					$(\"#bmemo\").focus();\r\n");
      out.write("					$(\"#bpw\").prop(\"readonly\", true);\r\n");
      out.write("					$(\".bsubject\").prop(\"readonly\", false);\r\n");
      out.write("					$(\".bsubject\").css(\"background-color\", \"#e6ffe6\");\r\n");
      out.write("					$(\".bmemo\").prop(\"readonly\", false);\r\n");
      out.write("					$(\".bmemo\").css(\"background-color\", \"#e6ffe6\");\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("				else{\r\n");
      out.write("					alert(\"비밀번호가 확인 되지 않았습니다.\");\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			function whenError(){\r\n");
      out.write("				alert(\"error >>> : \");\r\n");
      out.write("			}\r\n");
      out.write("		\r\n");
      out.write("		}); // end of click function\r\n");
      out.write("	});  // end of jQuery ready function\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>boardSelect.jsp 페이지입니다.</h1>\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');

	Logger logger=LogManager.getLogger(this.getClass());

	Object obj=request.getAttribute("aList_select");
	if(obj==null) return;
	
	ArrayList<BoardVO> aList=(ArrayList<BoardVO>) obj;
	logger.info("aList.size() >>> : "+aList.size());
	logger.info("aList.get(0) >>> : "+aList.get(0));
	/*
	BNUM       NOT NULL VARCHAR2(20)   
    BSUBJECT   NOT NULL VARCHAR2(100)  
    BWRITER             VARCHAR2(30)   
    BPW                 VARCHAR2(300)  
    BMEMO               VARCHAR2(2000) 
    DELETEYN   NOT NULL VARCHAR2(1)    
    INSERTDATE          DATE           
    UPDATEDATE          DATE           
	
	*/
	
	
	if(aList!=null && aList.size()>0){
	// 짧게 쓰는 로직 : if(!(aList!=null && aList.size()>0)) return;

      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("글 제목			길이 100\r\n");
      out.write("BSUBJECT		VARCHAR2(100)\r\n");
      out.write("글쓴이			길이 50\r\n");
      out.write("BWRITER		VARCHAR2(30)\r\n");
      out.write("글 쓸때 사용한 패스워드	길이 300 8자리 이상 : 단방향 암호화\r\n");
      out.write("BPW			VARCHAR2(300)\r\n");
      out.write("글 내용			길이 2000자\r\n");
      out.write("BMEMO			VARCHAR2(2000)\r\n");
      out.write(" -->\r\n");
      out.write("<table>\r\n");

		BoardVO _bvo=aList.get(0);
		logger.info("글번호 >>> : "+_bvo.getBnum());
		logger.info("글제목 >>> : "+_bvo.getBsubject());
		logger.info("글쓴이 >>> : "+_bvo.getBwriter());
		logger.info("글내용 >>> : "+_bvo.getBmemo());
		logger.info("회원여부 >>> : "+_bvo.getDeleteyn());
		logger.info("수정일 >>> : "+_bvo.getUpdatedate());

      out.write("				\r\n");
      out.write("<!-- \r\n");
      out.write(" 수정이 가능한 목록\r\n");
      out.write("  BSUBJECT :: 글 제목\r\n");
      out.write("BMEMO    :: 글 내용\r\n");
      out.write(" -->	\r\n");
      out.write("<form class=\"f1\" id=\"f1\" name=\"f1\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<!--  글번호 -->\r\n");
      out.write("			<tr>\r\n");
      out.write("			<td style=\"background-color:#e6ffe6\">글번호(수정불가)</td>\r\n");
      out.write("			<td><input style=\"width:170%; background-color:#e6e6e6;\" type=\"text\" class=\"bnum\" id=\"bnum\" name=\"bnum\" required maxlength=\"100\" placeholder=\"글 번호\" value=\"");
      out.print( _bvo.getBnum() );
      out.write("\" readonly></td>\r\n");
      out.write("			</tr>		\r\n");
      out.write("			<tr>\r\n");
      out.write("			<!--  글제목 -->\r\n");
      out.write("			<td style=\"background-color:#e6ffe6\">글제목(수정가능)</td>\r\n");
      out.write("			<td><input style=\"width:170%; background-color:#e6e6e6;\" type=\"text\" class=\"bsubject\" id=\"bsubject\" name=\"bsubject\" maxlength=\"30\" placeholder=\"수정할 글제목\" value=\"");
      out.print(_bvo.getBsubject() );
      out.write("\" readonly></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			<!--  글쓴이 -->\r\n");
      out.write("			<td style=\"background-color:#e6ffe6\">글쓴이(수정불가)</td>\r\n");
      out.write("			<td><input style=\"width:170%; background-color:#e6e6e6;\" type=\"text\" class=\"bwriter\" id=\"bwriter\" name=\"bwriter\" maxlength=\"30\" placeholder=\"글쓴이 수정\" value=\"");
      out.print(_bvo.getBwriter() );
      out.write("\" readonly></td>\r\n");
      out.write("			</tr>	\r\n");
      out.write("			<tr>\r\n");
      out.write("			<!--  비밀번호 -->\r\n");
      out.write("			<td style=\"background-color:#e6ffe6\">비밀번호(수정불가)</td>\r\n");
      out.write("			<td><input type=\"password\" style=\"width:100%; background-color:#e6ffe6\";\" class=\"bpw\" name=\"bpw\" id=\"bpw\"\r\n");
      out.write("				placeholder=\"비밀번호는 8자리로\" maxlength=\"8\" />	\r\n");
      out.write("				<input style=\"width:70%;\" type=\"button\" name=\"bpwChk\" id=\"bpwChk\" value=\"비밀번호확인\">\r\n");
      out.write("			</td>	\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			<!--  글내용 -->\r\n");
      out.write("			<td style=\"background-color:#e6ffe6\">글내용(수정가능)</td>\r\n");
      out.write("			<td><textarea style=\"width:170%; height:200%; background-color:#e6e6e6;\" class=\"bmemo\" id=\"bmemo\" name=\"bmemo\" maxlength=\"2000\" width=\"500px\" height=\"500px\" value=\"");
      out.print( _bvo.getBmemo() );
      out.write("\" placeholder=\"수정할 글내용\" value=\"");
      out.print( _bvo.getBmemo()  );
      out.write("\" readonly></textarea></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			<!--  회원여부 -->\r\n");
      out.write("			<td style=\"background-color:#e6ffe6\">회원여부(수정불가)</td>\r\n");
      out.write("			<td><input style=\"width:170%; background-color:#e6e6e6;\" type=\"text\" class=\"deleteyn\" id=\"deleteyn\" name=\"deleteyn\" maxlength=\"30\" placeholder=\"회원여부\" value=\"");
      out.print(_bvo.getDeleteyn() );
      out.write("\" readonly></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			<!--  등록일 -->\r\n");
      out.write("			<td style=\"background-color:#e6ffe6\">등록일(수정불가)</td>\r\n");
      out.write("			<td><input style=\"width:170%; background-color:#e6e6e6;\" type=\"text\" style=\"width:250px;\" value=\"");
      out.print( _bvo.getInsertdate() );
      out.write("\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			<!--  수정일 -->\r\n");
      out.write("			<td style=\"background-color:#e6ffe6\">수정일(수정불가)</td>\r\n");
      out.write("			<td><input style=\"width:170%; background-color:#e6e6e6;\" type=\"text\" class=\"updatedate\" id=\"updatedate\" name=\"updatedate\" maxlength=\"30\" placeholder=\"수정일\" value=\"");
      out.print(_bvo.getUpdatedate() );
      out.write("\" readonly></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<!-- 버튼 -->\r\n");
      out.write("			<input type=\"hidden\" name=\"isudType\" id=\"isudType\" name=\"isudType\" value=\"UOK\" />\r\n");
      out.write("			<tr>\r\n");
      out.write("			<td><input style=\"width:170%; background-color:#e6f2ff;\" type=\"button\" id=\"update_btn\" value=\"수정\" ></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			<td><input style=\"width:170%; background-color:#e6f2ff;\" type=\"button\" id=\"insert_btn\" value=\"글쓰기\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			<td><input style=\"width:170%; background-color:#e6f2ff;\" type=\"button\" id=\"selectAllBtn\" value=\"목록\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			<td><input style=\"width:170%; background-color:#e6f2ff;\" type=\"reset\"  value=\"취소\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("</form>\r\n");
			
	}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
